import type { AreaDefinition } from "./types";

const WORLD = {
  width: 1120,
  height: 630,
  safeBounds: { x: 32, y: 32, width: 1056, height: 566 },
} as const;

export const AREA_DEFINITIONS: readonly AreaDefinition[] = [
  {
    id: "area_waiting_room",
    name: "待合室",
    subtitle: "止まった時計と橙色の灯り",
    description: "濡れた木床に古いベンチが並ぶ待合室。窓の外では絶えず雨が線路を隠している。",
    availableFromStage: 0,
    objective: "傘立て、乗客、写真機を調べ、物と人に共通する印を探す。",
    world: WORLD,
    playerStart: { x: 320, y: 360, facing: "down" },
    palette: {
      floor: "#26384a",
      wall: "#172737",
      trim: "#6b6559",
      light: "#e2bd72",
      shadow: "#101a27",
      rain: "#78a6bd",
    },
    ambience: { rainLevel: "heavy", roomTone: "窓とトタン屋根を打つ近い雨", lightLevel: 0.62 },
    exits: [
      {
        id: "exit_waiting_to_concourse",
        label: "改札口へ",
        bounds: { x: 1060, y: 270, width: 60, height: 92 },
        targetAreaId: "area_concourse",
        targetPosition: { x: 88, y: 315, facing: "right" },
        availableFromStage: 0,
      },
    ],
    obstacles: [
      { id: "waiting_wall_north", label: "北壁", bounds: { x: 0, y: 0, width: 1120, height: 32 }, blocksMovement: true },
      { id: "waiting_wall_south", label: "南壁", bounds: { x: 0, y: 598, width: 1120, height: 32 }, blocksMovement: true },
      { id: "waiting_wall_west", label: "西壁", bounds: { x: 0, y: 0, width: 32, height: 630 }, blocksMovement: true },
      { id: "waiting_wall_east_top", label: "東壁", bounds: { x: 1088, y: 0, width: 32, height: 270 }, blocksMovement: true },
      { id: "waiting_wall_east_bottom", label: "東壁", bounds: { x: 1088, y: 362, width: 32, height: 268 }, blocksMovement: true },
      { id: "waiting_umbrella_rack", label: "傘立て", bounds: { x: 162, y: 326, width: 116, height: 106 }, blocksMovement: true },
      { id: "waiting_center_bench", label: "中央ベンチ", bounds: { x: 482, y: 178, width: 270, height: 62 }, blocksMovement: true },
      { id: "waiting_window_bench", label: "窓側ベンチ", bounds: { x: 742, y: 322, width: 194, height: 58 }, blocksMovement: true },
      { id: "waiting_photo_booth", label: "写真機", bounds: { x: 884, y: 82, width: 130, height: 194 }, blocksMovement: true },
    ],
    hotspots: [
      {
        id: "waiting_umbrella_stand",
        kind: "item",
        label: "赤い傘",
        prompt: "傘立てを調べる",
        position: { x: 220, y: 392 },
        radius: 86,
        facing: "left",
        itemId: "item_red_umbrella",
        clueId: "clue_umbrella_star_patch",
        availability: { availableFromStage: 0 },
      },
      {
        id: "waiting_umbrella_footprints",
        kind: "clue",
        label: "濡れた足跡",
        prompt: "床の足跡を見る",
        position: { x: 340, y: 466 },
        radius: 62,
        clueId: "clue_umbrella_footprints",
        availability: { availableFromStage: 0 },
      },
      {
        id: "waiting_red_boots_child",
        kind: "owner",
        label: "赤い長靴の子",
        prompt: "声をかける",
        position: { x: 824, y: 386 },
        radius: 76,
        ownerId: "owner_red_boots_child",
        dialogId: "dialog_owner_child_ambient",
        repeatDialogId: "dialog_owner_child_returned",
        availability: { availableFromStage: 0 },
      },
      {
        id: "waiting_old_listener",
        kind: "owner",
        label: "耳を澄ます老人",
        prompt: "指先の拍子を聞く",
        position: { x: 612, y: 246 },
        radius: 76,
        ownerId: "owner_old_listener",
        clueId: "clue_cassette_four_beats",
        dialogId: "dialog_owner_old_listener_ambient",
        repeatDialogId: "dialog_owner_old_listener_returned",
        availability: { availableFromStage: 0 },
      },
      {
        id: "waiting_photo_booth_dormant",
        kind: "inspect",
        label: "停止した写真機",
        prompt: "写真機を見る",
        position: { x: 944, y: 282 },
        radius: 74,
        dialogId: "dialog_waiting_photo_booth_dormant",
        availability: { availableFromStage: 0, availableUntilStage: 3 },
      },
      {
        id: "waiting_photo_booth_output",
        kind: "item",
        label: "写真機の取り出し口",
        prompt: "光る写真を取る",
        position: { x: 944, y: 282 },
        radius: 74,
        itemId: "item_faded_photo_sticker",
        clueId: "clue_photo_booth_code",
        availability: {
          availableFromStage: 4,
          requiresReturnedItemIds: [
            "item_red_umbrella",
            "item_star_bento",
            "item_cassette_player",
            "item_silver_hairclip",
          ],
        },
      },
      {
        id: "waiting_clock",
        kind: "inspect",
        label: "止まった時計",
        prompt: "時計を見る",
        position: { x: 554, y: 86 },
        radius: 70,
        dialogId: "dialog_waiting_clock",
        availability: { availableFromStage: 0 },
      },
      {
        id: "waiting_rain_window",
        kind: "inspect",
        label: "雨の窓",
        prompt: "外を見る",
        position: { x: 290, y: 92 },
        radius: 72,
        dialogId: "dialog_waiting_window",
        availability: { availableFromStage: 0 },
      },
    ],
    decorations: [
      { id: "waiting_floor_band", kind: "floor-band", bounds: { x: 32, y: 436, width: 1056, height: 8 }, layer: "floor", color: "#b79861", opacity: 0.45 },
      { id: "waiting_window", kind: "window", bounds: { x: 122, y: 40, width: 342, height: 94 }, layer: "above-player", color: "#183144", accentColor: "#78a6bd", animation: "rain" },
      { id: "waiting_clock_decor", kind: "clock", bounds: { x: 512, y: 42, width: 84, height: 84 }, layer: "above-player", color: "#d5c79d", accentColor: "#233247", animation: "clock" },
      { id: "waiting_lamp_left", kind: "lamp", bounds: { x: 392, y: 76, width: 28, height: 28 }, layer: "above-player", color: "#e2bd72", animation: "pulse" },
      { id: "waiting_lamp_right", kind: "lamp", bounds: { x: 762, y: 76, width: 28, height: 28 }, layer: "above-player", color: "#e2bd72", animation: "pulse" },
      { id: "waiting_station_poster", kind: "poster", bounds: { x: 60, y: 160, width: 72, height: 116 }, layer: "above-player", color: "#667d7a", accentColor: "#d7c584", label: "雨の日も足元にお気をつけて" },
      { id: "waiting_door", kind: "door", bounds: { x: 1062, y: 270, width: 58, height: 92 }, layer: "floor", color: "#40556a", accentColor: "#d5bd79", label: "改札口" },
    ],
  },
  {
    id: "area_concourse",
    name: "改札口と券売機",
    subtitle: "夜を量る駅の中心",
    description: "改札機と券売機の青白い灯りが並ぶ構内。顔の見えない駅員が窓口に立つ。",
    availableFromStage: 0,
    objective: "駅員の案内を聞き、開いた扉と乗客の持ち物を確認する。",
    world: WORLD,
    playerStart: { x: 88, y: 315, facing: "right" },
    palette: { floor: "#223546", wall: "#132536", trim: "#557179", light: "#cbbd7d", shadow: "#0d1925", rain: "#709ab0" },
    ambience: { rainLevel: "steady", roomTone: "高い天井に反響する雨と券売機の低音", lightLevel: 0.56 },
    exits: [
      {
        id: "exit_concourse_to_waiting",
        label: "待合室へ",
        bounds: { x: 0, y: 270, width: 60, height: 92 },
        targetAreaId: "area_waiting_room",
        targetPosition: { x: 1020, y: 315, facing: "left" },
        availableFromStage: 0,
      },
      {
        id: "exit_concourse_to_office",
        label: "駅員室へ",
        bounds: { x: 276, y: 0, width: 126, height: 60 },
        targetAreaId: "area_station_office",
        targetPosition: { x: 554, y: 548, facing: "up" },
        availableFromStage: 1,
        lockedDialogId: "dialog_exit_station_office_locked",
      },
      {
        id: "exit_concourse_to_footbridge",
        label: "跨線橋へ",
        bounds: { x: 1060, y: 158, width: 60, height: 96 },
        targetAreaId: "area_footbridge",
        targetPosition: { x: 88, y: 315, facing: "right" },
        availableFromStage: 2,
        lockedDialogId: "dialog_exit_footbridge_locked",
      },
    ],
    obstacles: [
      { id: "concourse_wall_south", label: "南壁", bounds: { x: 0, y: 598, width: 1120, height: 32 }, blocksMovement: true },
      { id: "concourse_wall_west_top", label: "西壁", bounds: { x: 0, y: 0, width: 32, height: 270 }, blocksMovement: true },
      { id: "concourse_wall_west_bottom", label: "西壁", bounds: { x: 0, y: 362, width: 32, height: 268 }, blocksMovement: true },
      { id: "concourse_counter", label: "駅員窓口", bounds: { x: 438, y: 108, width: 226, height: 88 }, blocksMovement: true },
      { id: "concourse_ticket_machine", label: "券売機", bounds: { x: 714, y: 96, width: 118, height: 162 }, blocksMovement: true },
      { id: "concourse_phone", label: "公衆電話", bounds: { x: 924, y: 98, width: 88, height: 134 }, blocksMovement: true },
      { id: "concourse_bench", label: "長椅子", bounds: { x: 704, y: 326, width: 244, height: 60 }, blocksMovement: true },
      { id: "concourse_gate_bank", label: "改札機", bounds: { x: 324, y: 470, width: 460, height: 54 }, blocksMovement: true },
    ],
    hotspots: [
      {
        id: "concourse_station_attendant",
        kind: "owner",
        label: "顔の見えない駅員",
        prompt: "駅員に尋ねる",
        position: { x: 548, y: 214 },
        radius: 82,
        ownerId: "owner_station_attendant",
        dialogId: "dialog_attendant_intro",
        repeatDialogId: "dialog_owner_station_attendant_ambient",
        availability: { availableFromStage: 0 },
      },
      {
        id: "concourse_navy_bag_commuter",
        kind: "owner",
        label: "紺の鞄の通勤客",
        prompt: "声をかける",
        position: { x: 822, y: 400 },
        radius: 78,
        ownerId: "owner_navy_bag_commuter",
        dialogId: "dialog_owner_commuter_ambient",
        repeatDialogId: "dialog_owner_commuter_returned",
        availability: { availableFromStage: 0 },
      },
      {
        id: "concourse_commuter_bag",
        kind: "clue",
        label: "紺の鞄",
        prompt: "結ばれた布を見る",
        position: { x: 904, y: 404 },
        radius: 54,
        clueId: "clue_bento_navy_wrap",
        availability: { availableFromStage: 0 },
      },
      {
        id: "concourse_ticket_machine_dormant",
        kind: "inspect",
        label: "券売機",
        prompt: "表示を見る",
        position: { x: 772, y: 274 },
        radius: 70,
        dialogId: "dialog_concourse_timetable",
        availability: { availableFromStage: 0, availableUntilStage: 4 },
      },
      {
        id: "concourse_ticket_machine",
        kind: "item",
        label: "白紙の切符",
        prompt: "券売機の切符を取る",
        position: { x: 772, y: 274 },
        radius: 70,
        itemId: "item_blank_ticket",
        clueId: "clue_ticket_pocket_fragment",
        availability: {
          availableFromStage: 5,
          requiresReturnedItemIds: [
            "item_red_umbrella",
            "item_star_bento",
            "item_cassette_player",
            "item_silver_hairclip",
            "item_faded_photo_sticker",
          ],
        },
      },
      {
        id: "concourse_gate",
        kind: "inspect",
        label: "閉じた改札",
        prompt: "改札表示を見る",
        position: { x: 554, y: 448 },
        radius: 62,
        dialogId: "dialog_concourse_gate",
        availability: { availableFromStage: 0 },
      },
      {
        id: "concourse_timetable",
        kind: "inspect",
        label: "時刻表",
        prompt: "時刻表を読む",
        position: { x: 164, y: 104 },
        radius: 66,
        dialogId: "dialog_concourse_timetable",
        availability: { availableFromStage: 0 },
      },
      {
        id: "concourse_phone_hotspot",
        kind: "inspect",
        label: "公衆電話",
        prompt: "受話器を取る",
        position: { x: 968, y: 252 },
        radius: 66,
        dialogId: "dialog_concourse_phone",
        availability: { availableFromStage: 0 },
      },
    ],
    decorations: [
      { id: "concourse_route_band", kind: "floor-band", bounds: { x: 42, y: 296, width: 1036, height: 38 }, layer: "floor", color: "#557b80", opacity: 0.34 },
      { id: "concourse_counter_decor", kind: "counter", bounds: { x: 438, y: 108, width: 226, height: 88 }, layer: "below-player", color: "#26384a", accentColor: "#d0b96f", label: "きっぷ・案内" },
      { id: "concourse_machine_decor", kind: "machine", bounds: { x: 714, y: 96, width: 118, height: 162 }, layer: "below-player", color: "#3d5360", accentColor: "#8eb5b9", animation: "pulse" },
      { id: "concourse_clock", kind: "clock", bounds: { x: 530, y: 38, width: 62, height: 62 }, layer: "above-player", color: "#d5c79d", accentColor: "#213245", animation: "clock" },
      { id: "concourse_timetable_decor", kind: "sign", bounds: { x: 96, y: 44, width: 140, height: 120 }, layer: "above-player", color: "#d6d5c8", accentColor: "#2e4654", label: "発車時刻" },
      { id: "concourse_office_door", kind: "door", bounds: { x: 276, y: 0, width: 126, height: 60 }, layer: "floor", color: "#334a5b", accentColor: "#d4b963", label: "駅員室" },
      { id: "concourse_stairs", kind: "stairs", bounds: { x: 1018, y: 158, width: 102, height: 96 }, layer: "floor", color: "#344b5a", accentColor: "#69808b", label: "跨線橋" },
    ],
  },
  {
    id: "area_station_office",
    name: "駅員室",
    subtitle: "台帳と一拍早い鏡",
    description: "使われなくなった机と台帳が残る小部屋。壁の鏡だけが現実より一拍早く動く。",
    availableFromStage: 1,
    objective: "冷蔵庫、台帳、鏡を調べ、駅員室に残る持ち物の来歴を確かめる。",
    world: WORLD,
    playerStart: { x: 554, y: 548, facing: "up" },
    palette: { floor: "#2b3942", wall: "#1a2933", trim: "#746852", light: "#d7b774", shadow: "#101820", rain: "#6e93a6" },
    ambience: { rainLevel: "steady", roomTone: "壁越しの雨と古い冷蔵庫の唸り", lightLevel: 0.58 },
    exits: [
      {
        id: "exit_office_to_concourse",
        label: "改札口へ戻る",
        bounds: { x: 488, y: 570, width: 140, height: 60 },
        targetAreaId: "area_concourse",
        targetPosition: { x: 338, y: 92, facing: "down" },
        availableFromStage: 1,
      },
    ],
    obstacles: [
      { id: "office_wall_north", label: "北壁", bounds: { x: 0, y: 0, width: 1120, height: 32 }, blocksMovement: true },
      { id: "office_wall_west", label: "西壁", bounds: { x: 0, y: 0, width: 32, height: 630 }, blocksMovement: true },
      { id: "office_wall_east", label: "東壁", bounds: { x: 1088, y: 0, width: 32, height: 630 }, blocksMovement: true },
      { id: "office_refrigerator_body", label: "冷蔵庫", bounds: { x: 112, y: 104, width: 148, height: 198 }, blocksMovement: true },
      { id: "office_desk", label: "事務机", bounds: { x: 392, y: 258, width: 326, height: 124 }, blocksMovement: true },
      { id: "office_shelf", label: "書類棚", bounds: { x: 858, y: 92, width: 142, height: 218 }, blocksMovement: true },
      { id: "office_chair", label: "椅子", bounds: { x: 520, y: 408, width: 76, height: 64 }, blocksMovement: true },
    ],
    hotspots: [
      {
        id: "office_refrigerator",
        kind: "item",
        label: "古い冷蔵庫",
        prompt: "冷蔵庫を開ける",
        position: { x: 190, y: 320 },
        radius: 84,
        itemId: "item_star_bento",
        clueId: "clue_bento_lid_note",
        availability: { availableFromStage: 1, requiresReturnedItemIds: ["item_red_umbrella"] },
      },
      {
        id: "office_moon_youth",
        kind: "owner",
        label: "月のピンの青年",
        prompt: "写真袋について聞く",
        position: { x: 838, y: 382 },
        radius: 78,
        ownerId: "owner_crescent_youth",
        clueId: "clue_photo_crescent_pin",
        dialogId: "dialog_owner_youth_ambient",
        repeatDialogId: "dialog_owner_youth_returned",
        availability: { availableFromStage: 1 },
      },
      {
        id: "office_mirror_early",
        kind: "inspect",
        label: "壁の鏡",
        prompt: "鏡を見る",
        position: { x: 554, y: 156 },
        radius: 82,
        dialogId: "dialog_office_mirror",
        availability: { availableFromStage: 1, availableUntilStage: 4 },
      },
      {
        id: "office_mirror",
        kind: "mirror",
        label: "鏡の中のナギ",
        prompt: "鏡像へ切符を差し出す",
        position: { x: 554, y: 156 },
        radius: 82,
        ownerId: "owner_nagi",
        clueId: "clue_ticket_reflection",
        dialogId: "dialog_owner_nagi_ambient",
        repeatDialogId: "dialog_owner_nagi_returned",
        availability: { availableFromStage: 5 },
      },
      {
        id: "office_ledger",
        kind: "inspect",
        label: "遺失物台帳",
        prompt: "台帳を読む",
        position: { x: 456, y: 238 },
        radius: 62,
        dialogId: "dialog_office_ledger",
        availability: { availableFromStage: 1 },
      },
      {
        id: "office_key_board",
        kind: "inspect",
        label: "鍵札",
        prompt: "鍵札を読む",
        position: { x: 780, y: 116 },
        radius: 62,
        dialogId: "dialog_office_keys",
        availability: { availableFromStage: 1 },
      },
    ],
    decorations: [
      { id: "office_desk_decor", kind: "counter", bounds: { x: 392, y: 258, width: 326, height: 124 }, layer: "below-player", color: "#554c3f", accentColor: "#88775b" },
      { id: "office_fridge_decor", kind: "machine", bounds: { x: 112, y: 104, width: 148, height: 198 }, layer: "below-player", color: "#71807e", accentColor: "#b4c3ba" },
      { id: "office_mirror_decor", kind: "window", bounds: { x: 492, y: 48, width: 124, height: 122 }, layer: "above-player", color: "#607789", accentColor: "#a8c1ca", animation: "reflection" },
      { id: "office_shelf_decor", kind: "shelf", bounds: { x: 858, y: 92, width: 142, height: 218 }, layer: "below-player", color: "#3f4a4c", accentColor: "#766f5a" },
      { id: "office_key_sign", kind: "sign", bounds: { x: 738, y: 60, width: 84, height: 82 }, layer: "above-player", color: "#504b3d", accentColor: "#d2ba76", label: "鍵札" },
      { id: "office_lamp", kind: "lamp", bounds: { x: 654, y: 72, width: 28, height: 28 }, layer: "above-player", color: "#d7b774", animation: "pulse" },
      { id: "office_exit_door", kind: "door", bounds: { x: 488, y: 570, width: 140, height: 60 }, layer: "floor", color: "#40515a", accentColor: "#c5a969", label: "改札口" },
    ],
  },
  {
    id: "area_footbridge",
    name: "跨線橋",
    subtitle: "雨音を見下ろす通路",
    description: "線路をまたぐ長い通路。高窓と手すりの向こうに、雨で消えた町の輪郭が見える。",
    availableFromStage: 2,
    objective: "ベンチ下の回転音と、本を抱く学生の印を調べる。",
    world: WORLD,
    playerStart: { x: 88, y: 315, facing: "right" },
    palette: { floor: "#25394a", wall: "#142738", trim: "#607883", light: "#c6b879", shadow: "#0d1a27", rain: "#7ba9c0" },
    ambience: { rainLevel: "heavy", roomTone: "ガラス屋根を流れる雨と金属のきしみ", lightLevel: 0.5 },
    exits: [
      {
        id: "exit_footbridge_to_concourse",
        label: "改札口へ戻る",
        bounds: { x: 0, y: 270, width: 60, height: 92 },
        targetAreaId: "area_concourse",
        targetPosition: { x: 1020, y: 206, facing: "left" },
        availableFromStage: 2,
      },
      {
        id: "exit_footbridge_to_platform",
        label: "雨のホームへ",
        bounds: { x: 854, y: 570, width: 130, height: 60 },
        targetAreaId: "area_rain_platform",
        targetPosition: { x: 220, y: 108, facing: "down" },
        availableFromStage: 3,
        lockedDialogId: "dialog_exit_platform_locked",
      },
    ],
    obstacles: [
      { id: "footbridge_wall_north", label: "北壁", bounds: { x: 0, y: 0, width: 1120, height: 32 }, blocksMovement: true },
      { id: "footbridge_wall_east", label: "東壁", bounds: { x: 1088, y: 0, width: 32, height: 630 }, blocksMovement: true },
      { id: "footbridge_wall_west_top", label: "西壁", bounds: { x: 0, y: 0, width: 32, height: 270 }, blocksMovement: true },
      { id: "footbridge_wall_west_bottom", label: "西壁", bounds: { x: 0, y: 362, width: 32, height: 268 }, blocksMovement: true },
      { id: "footbridge_cassette_bench_body", label: "木のベンチ", bounds: { x: 216, y: 330, width: 226, height: 62 }, blocksMovement: true },
      { id: "footbridge_student_bench", label: "窓側ベンチ", bounds: { x: 690, y: 208, width: 218, height: 58 }, blocksMovement: true },
      { id: "footbridge_railing_left", label: "手すり", bounds: { x: 74, y: 506, width: 760, height: 28 }, blocksMovement: true },
      { id: "footbridge_railing_right", label: "手すり", bounds: { x: 1000, y: 506, width: 82, height: 28 }, blocksMovement: true },
    ],
    hotspots: [
      {
        id: "footbridge_cassette_bench",
        kind: "item",
        label: "ベンチ下の機械",
        prompt: "回転音を調べる",
        position: { x: 318, y: 410 },
        radius: 78,
        itemId: "item_cassette_player",
        clueId: "clue_cassette_blue_thread",
        availability: {
          availableFromStage: 2,
          requiresReturnedItemIds: ["item_red_umbrella", "item_star_bento"],
        },
      },
      {
        id: "footbridge_ginkgo_student",
        kind: "owner",
        label: "本を抱く学生",
        prompt: "栞と名札を見る",
        position: { x: 770, y: 286 },
        radius: 80,
        ownerId: "owner_ginkgo_student",
        clueId: "clue_hairclip_bookmark_tag",
        dialogId: "dialog_owner_student_ambient",
        repeatDialogId: "dialog_owner_student_returned",
        availability: { availableFromStage: 2 },
      },
      {
        id: "footbridge_high_window",
        kind: "inspect",
        label: "高窓",
        prompt: "夜空を見る",
        position: { x: 520, y: 112 },
        radius: 72,
        dialogId: "dialog_footbridge_window",
        availability: { availableFromStage: 2 },
      },
      {
        id: "footbridge_notice",
        kind: "inspect",
        label: "古い掲示",
        prompt: "書き込みを読む",
        position: { x: 974, y: 130 },
        radius: 66,
        dialogId: "dialog_footbridge_notice",
        availability: { availableFromStage: 2 },
      },
      {
        id: "footbridge_railing",
        kind: "inspect",
        label: "冷たい手すり",
        prompt: "雨音を聞く",
        position: { x: 584, y: 480 },
        radius: 70,
        dialogId: "dialog_footbridge_railing",
        availability: { availableFromStage: 2 },
      },
    ],
    decorations: [
      { id: "footbridge_window_strip", kind: "window", bounds: { x: 120, y: 42, width: 776, height: 116 }, layer: "above-player", color: "#122f43", accentColor: "#7ba9c0", animation: "rain" },
      { id: "footbridge_bench_decor", kind: "bench", bounds: { x: 216, y: 330, width: 226, height: 62 }, layer: "below-player", color: "#51493d", accentColor: "#85735b" },
      { id: "footbridge_student_bench_decor", kind: "bench", bounds: { x: 690, y: 208, width: 218, height: 58 }, layer: "below-player", color: "#51493d", accentColor: "#85735b" },
      { id: "footbridge_railing_decor", kind: "railing", bounds: { x: 74, y: 506, width: 1008, height: 28 }, layer: "above-player", color: "#5c717a", accentColor: "#94a6aa" },
      { id: "footbridge_notice_decor", kind: "poster", bounds: { x: 940, y: 70, width: 90, height: 112 }, layer: "above-player", color: "#d1c9ad", accentColor: "#5e625c", label: "別れの言葉は乗車前に" },
      { id: "footbridge_stair_decor", kind: "stairs", bounds: { x: 854, y: 514, width: 130, height: 116 }, layer: "floor", color: "#344a58", accentColor: "#718690", label: "ホーム" },
      { id: "footbridge_lamp", kind: "lamp", bounds: { x: 548, y: 178, width: 28, height: 28 }, layer: "above-player", color: "#c6b879", animation: "pulse" },
    ],
  },
  {
    id: "area_rain_platform",
    name: "雨のホーム",
    subtitle: "終電と朝の境目",
    description: "吹き込む雨に濡れたホーム。線路は闇へ続き、水たまりだけが早い朝を映している。",
    availableFromStage: 3,
    objective: "排水溝の光を確かめ、すべてを返したら到着する列車の前で行き先を選ぶ。",
    world: WORLD,
    playerStart: { x: 220, y: 108, facing: "down" },
    palette: { floor: "#203746", wall: "#102331", trim: "#52747e", light: "#d2bd77", shadow: "#091722", rain: "#82b4ca" },
    ambience: { rainLevel: "heavy", roomTone: "吹き込む雨、遠いレール、時折鳴る風鈴", lightLevel: 0.46 },
    exits: [
      {
        id: "exit_platform_to_footbridge",
        label: "跨線橋へ戻る",
        bounds: { x: 158, y: 0, width: 126, height: 60 },
        targetAreaId: "area_footbridge",
        targetPosition: { x: 918, y: 548, facing: "up" },
        availableFromStage: 3,
      },
    ],
    obstacles: [
      { id: "platform_wall_north_left", label: "北壁", bounds: { x: 0, y: 0, width: 158, height: 32 }, blocksMovement: true },
      { id: "platform_wall_north_right", label: "北壁", bounds: { x: 284, y: 0, width: 836, height: 32 }, blocksMovement: true },
      { id: "platform_wall_west", label: "西壁", bounds: { x: 0, y: 0, width: 32, height: 630 }, blocksMovement: true },
      { id: "platform_wall_east", label: "東壁", bounds: { x: 1088, y: 0, width: 32, height: 630 }, blocksMovement: true },
      { id: "platform_track", label: "線路", bounds: { x: 32, y: 486, width: 1056, height: 144 }, blocksMovement: true },
      { id: "platform_bench", label: "ホームのベンチ", bounds: { x: 248, y: 244, width: 248, height: 62 }, blocksMovement: true },
      { id: "platform_vending_body", label: "自動販売機", bounds: { x: 892, y: 92, width: 118, height: 184 }, blocksMovement: true },
      { id: "platform_sign_post", label: "駅名標", bounds: { x: 544, y: 88, width: 36, height: 146 }, blocksMovement: true },
    ],
    hotspots: [
      {
        id: "platform_drain_hairclip",
        kind: "item",
        label: "排水溝の銀色の光",
        prompt: "排水溝を調べる",
        position: { x: 650, y: 446 },
        radius: 76,
        itemId: "item_silver_hairclip",
        clueId: "clue_hairclip_engraving",
        availability: {
          availableFromStage: 3,
          requiresReturnedItemIds: [
            "item_red_umbrella",
            "item_star_bento",
            "item_cassette_player",
          ],
        },
      },
      {
        id: "platform_station_sign",
        kind: "inspect",
        label: "雨ノ間の駅名標",
        prompt: "駅名標を読む",
        position: { x: 562, y: 238 },
        radius: 64,
        dialogId: "dialog_platform_sign",
        availability: { availableFromStage: 3 },
      },
      {
        id: "platform_vending_machine",
        kind: "inspect",
        label: "古い自動販売機",
        prompt: "商品灯を見る",
        position: { x: 950, y: 296 },
        radius: 68,
        dialogId: "dialog_platform_vending",
        availability: { availableFromStage: 3 },
      },
      {
        id: "platform_puddle",
        kind: "inspect",
        label: "空を映す水たまり",
        prompt: "水面を見る",
        position: { x: 372, y: 392 },
        radius: 72,
        dialogId: "dialog_platform_puddle",
        availability: { availableFromStage: 3 },
      },
      {
        id: "platform_last_train",
        kind: "ending",
        label: "行き先のない終電",
        prompt: "終電の前で選ぶ",
        position: { x: 812, y: 434 },
        radius: 96,
        dialogId: "dialog_platform_last_train",
        availability: {
          availableFromStage: 5,
          availableUntilStage: 5,
          requiresReturnedItemIds: [
            "item_red_umbrella",
            "item_star_bento",
            "item_cassette_player",
            "item_silver_hairclip",
            "item_faded_photo_sticker",
          ],
        },
      },
      {
        id: "platform_dawn_train",
        kind: "ending",
        label: "朝を映す始発",
        prompt: "夜明けの行き先を選ぶ",
        position: { x: 812, y: 434 },
        radius: 96,
        dialogId: "dialog_platform_dawn",
        availability: {
          availableFromStage: 6,
          requiresReturnedItemIds: [
            "item_red_umbrella",
            "item_star_bento",
            "item_cassette_player",
            "item_silver_hairclip",
            "item_faded_photo_sticker",
            "item_blank_ticket",
          ],
        },
      },
    ],
    decorations: [
      { id: "platform_canopy", kind: "wall", bounds: { x: 32, y: 32, width: 1056, height: 56 }, layer: "above-player", color: "#142a38", accentColor: "#54727d" },
      { id: "platform_stairs", kind: "stairs", bounds: { x: 158, y: 0, width: 126, height: 112 }, layer: "floor", color: "#344d5a", accentColor: "#728a93", label: "跨線橋" },
      { id: "platform_bench_decor", kind: "bench", bounds: { x: 248, y: 244, width: 248, height: 62 }, layer: "below-player", color: "#4b4c47", accentColor: "#777a70" },
      { id: "platform_sign_decor", kind: "sign", bounds: { x: 490, y: 94, width: 144, height: 76 }, layer: "above-player", color: "#e0ded0", accentColor: "#345765", label: "雨ノ間" },
      { id: "platform_vending_decor", kind: "machine", bounds: { x: 892, y: 92, width: 118, height: 184 }, layer: "below-player", color: "#3c5862", accentColor: "#d8b66b", animation: "pulse" },
      { id: "platform_safety_line", kind: "floor-band", bounds: { x: 32, y: 448, width: 1056, height: 12 }, layer: "floor", color: "#d0b652", opacity: 0.72 },
      { id: "platform_drain", kind: "drain", bounds: { x: 568, y: 436, width: 166, height: 24 }, layer: "floor", color: "#101d25", accentColor: "#6f8790" },
      { id: "platform_tracks", kind: "track", bounds: { x: 32, y: 486, width: 1056, height: 144 }, layer: "floor", color: "#111d25", accentColor: "#6a7173" },
      { id: "platform_puddle_decor", kind: "puddle", bounds: { x: 286, y: 366, width: 172, height: 52 }, layer: "floor", color: "#507b8e", accentColor: "#9bc0cc", opacity: 0.58, animation: "reflection" },
      { id: "platform_rain_sheet", kind: "window", bounds: { x: 34, y: 460, width: 1052, height: 24 }, layer: "above-player", color: "#487789", accentColor: "#82b4ca", opacity: 0.42, animation: "rain" },
    ],
  },
] as const;
