import type { ClueDefinition } from "./types";

export const CLUE_DEFINITIONS: readonly ClueDefinition[] = [
  {
    id: "clue_umbrella_footprints",
    itemId: "item_red_umbrella",
    title: "小さな濡れ足跡",
    observation: "傘立てから窓側ベンチまで、子供ほどの小さな濡れ足跡が続いている。",
    notebookText: "赤い傘のそばから、小さな靴の乗客へ続く足跡。",
    areaId: "area_waiting_room",
    hotspotId: "waiting_umbrella_footprints",
    source: "world",
  },
  {
    id: "clue_umbrella_star_patch",
    itemId: "item_red_umbrella",
    title: "白い星の補修",
    observation: "赤い傘の端に、手縫いの白い星が一つ。子供の上着にも同じ縫い方がある。",
    notebookText: "傘と赤い長靴の子の上着に、同じ白い星。",
    areaId: "area_waiting_room",
    hotspotId: "waiting_umbrella_stand",
    source: "item",
  },
  {
    id: "clue_bento_lid_note",
    itemId: "item_star_bento",
    title: "蓋の短いメモ",
    observation: "星柄の蓋の裏に『お姉ちゃんへ。ちゃんと食べてね』と丸い字で書かれている。",
    notebookText: "妹から姉へ渡すはずだった弁当。",
    areaId: "area_station_office",
    hotspotId: "office_refrigerator",
    source: "item",
  },
  {
    id: "clue_bento_navy_wrap",
    itemId: "item_star_bento",
    title: "紺色の包み布",
    observation: "通勤客の鞄に結ばれた布は、弁当箱の包みと色も織り目も同じ。",
    notebookText: "弁当の包みと、紺の鞄に結ばれた布が一致。",
    areaId: "area_concourse",
    hotspotId: "concourse_commuter_bag",
    source: "owner",
  },
  {
    id: "clue_cassette_four_beats",
    itemId: "item_cassette_player",
    title: "四拍の雨音",
    observation: "老人の指は、屋根の雨と同じ四拍を繰り返す。録音の冒頭にも同じ間がある。",
    notebookText: "老人が刻む四拍と、カセットの雨音が一致。",
    areaId: "area_waiting_room",
    hotspotId: "waiting_old_listener",
    source: "owner",
  },
  {
    id: "clue_cassette_blue_thread",
    itemId: "item_cassette_player",
    title: "青い糸の直し跡",
    observation: "プレーヤーの布ケースと老人のヘッドホンが、同じ鮮やかな青糸で繕われている。",
    notebookText: "機械のケースと老人の耳当てに、同じ青糸。",
    areaId: "area_footbridge",
    hotspotId: "footbridge_cassette_bench",
    source: "item",
  },
  {
    id: "clue_hairclip_engraving",
    itemId: "item_silver_hairclip",
    title: "銀杏とKの刻印",
    observation: "銀色の髪留めの裏に、小さな銀杏とKの文字が刻まれている。",
    notebookText: "髪留めの裏に銀杏とK。",
    areaId: "area_rain_platform",
    hotspotId: "platform_drain_hairclip",
    source: "item",
  },
  {
    id: "clue_hairclip_bookmark_tag",
    itemId: "item_silver_hairclip",
    title: "栞と鞄の名札",
    observation: "学生の本には銀杏の栞、鞄にはKの名札。右の髪を何度も押さえている。",
    notebookText: "銀杏の栞とKの名札を持ち、右髪を気にする学生。",
    areaId: "area_footbridge",
    hotspotId: "footbridge_ginkgo_student",
    source: "owner",
  },
  {
    id: "clue_photo_crescent_pin",
    itemId: "item_faded_photo_sticker",
    title: "同じ三日月",
    observation: "写真の隅の三日月印は、駅員室の青年が襟につけたピンと同じ欠け方をしている。",
    notebookText: "写真の月印と、青年の三日月のピンが一致。",
    areaId: "area_station_office",
    hotspotId: "office_moon_youth",
    source: "owner",
  },
  {
    id: "clue_photo_booth_code",
    itemId: "item_faded_photo_sticker",
    title: "AM-042の番号",
    observation: "写真機の印字AM-042が、青年の持つ破れた写真袋の番号につながる。",
    notebookText: "写真と破れた袋の番号は、どちらもAM-042。",
    areaId: "area_waiting_room",
    hotspotId: "waiting_photo_booth_output",
    source: "item",
  },
  {
    id: "clue_ticket_pocket_fragment",
    itemId: "item_blank_ticket",
    title: "ポケットの紙片",
    observation: "制服の内ポケットから出た紙片が、白紙の切符の切断面にぴたりと重なる。",
    notebookText: "自分のポケットにあった紙片と、白紙の切符が一枚につながる。",
    areaId: "area_concourse",
    hotspotId: "concourse_ticket_machine",
    source: "item",
  },
  {
    id: "clue_ticket_reflection",
    itemId: "item_blank_ticket",
    title: "先回りする鏡像",
    observation: "切符を拾う前から、駅員室の鏡像だけが同じ白い紙を右手に持っていた。",
    notebookText: "鏡のナギは、拾う前から白紙の切符を持っていた。",
    areaId: "area_station_office",
    hotspotId: "office_mirror",
    source: "reflection",
  },
] as const;
