import type { LostItemDefinition, ObjectiveDefinition } from "./types";

export const LOST_ITEM_DEFINITIONS: readonly LostItemDefinition[] = [
  {
    id: "item_red_umbrella",
    name: "赤い傘",
    shortDescription: "白い星で繕われた子供用の傘",
    inventoryDescription: "小さな赤い傘。布端の裂け目を、白い星の布で丁寧に補修してある。",
    objective: "待合室の傘と濡れた足跡を調べ、持ち主を探す",
    stage: 0,
    spawn: {
      areaId: "area_waiting_room",
      hotspotId: "waiting_umbrella_stand",
      position: { x: 220, y: 392 },
      availableFromStage: 0,
      requiresReturnedItemIds: [],
    },
    ownerId: "owner_red_boots_child",
    clueIds: ["clue_umbrella_footprints", "clue_umbrella_star_patch"],
    wrongDialogIds: [
      "dialog_item_red_umbrella_wrong_1",
      "dialog_item_red_umbrella_wrong_2",
    ],
    hintDialogIds: [
      "dialog_item_red_umbrella_hint_1",
      "dialog_item_red_umbrella_hint_2",
      "dialog_item_red_umbrella_hint_3",
    ],
    memoryId: "memory_red_umbrella",
    correctDialogId: "dialog_item_red_umbrella_correct",
    note: "小さな足跡と白い星。窓側で待つ子供なら、両方につながる。",
    visual: {
      shape: "umbrella",
      primaryColor: "#c94f55",
      secondaryColor: "#f1e6bf",
      glyph: "☆",
    },
  },
  {
    id: "item_star_bento",
    name: "星柄の弁当箱",
    shortDescription: "『お姉ちゃんへ』と書かれた弁当箱",
    inventoryDescription: "小さな星が並ぶ弁当箱。紺色の布に包まれ、まだほのかに温かい。",
    objective: "開いた駅員室で弁当箱を見つけ、家族を気にする乗客へ返す",
    stage: 1,
    spawn: {
      areaId: "area_station_office",
      hotspotId: "office_refrigerator",
      position: { x: 190, y: 320 },
      availableFromStage: 1,
      requiresReturnedItemIds: ["item_red_umbrella"],
    },
    ownerId: "owner_navy_bag_commuter",
    clueIds: ["clue_bento_lid_note", "clue_bento_navy_wrap"],
    wrongDialogIds: [
      "dialog_item_star_bento_wrong_1",
      "dialog_item_star_bento_wrong_2",
    ],
    hintDialogIds: [
      "dialog_item_star_bento_hint_1",
      "dialog_item_star_bento_hint_2",
      "dialog_item_star_bento_hint_3",
    ],
    memoryId: "memory_star_bento",
    correctDialogId: "dialog_item_star_bento_correct",
    note: "妹から姉へのメモ。紺の包み布は、通勤客の鞄に結ばれた布と同じ。",
    visual: {
      shape: "bento",
      primaryColor: "#465f83",
      secondaryColor: "#e5c66b",
      glyph: "✦",
    },
  },
  {
    id: "item_cassette_player",
    name: "古いカセットプレーヤー",
    shortDescription: "四拍の雨音を録音した小さな機械",
    inventoryDescription: "角の丸いカセットプレーヤー。布ケースは青い糸で何度も繕われている。",
    objective: "灯った跨線橋で回転音のする機械を探し、雨音を知る人へ返す",
    stage: 2,
    spawn: {
      areaId: "area_footbridge",
      hotspotId: "footbridge_cassette_bench",
      position: { x: 318, y: 410 },
      availableFromStage: 2,
      requiresReturnedItemIds: ["item_red_umbrella", "item_star_bento"],
    },
    ownerId: "owner_old_listener",
    clueIds: ["clue_cassette_four_beats", "clue_cassette_blue_thread"],
    wrongDialogIds: [
      "dialog_item_cassette_player_wrong_1",
      "dialog_item_cassette_player_wrong_2",
    ],
    hintDialogIds: [
      "dialog_item_cassette_player_hint_1",
      "dialog_item_cassette_player_hint_2",
      "dialog_item_cassette_player_hint_3",
    ],
    memoryId: "memory_cassette_player",
    correctDialogId: "dialog_item_cassette_player_correct",
    note: "四拍の雨音と青い補修糸。待合室で耳を澄ます老人の癖に重なる。",
    visual: {
      shape: "cassette",
      primaryColor: "#596474",
      secondaryColor: "#4d9ac4",
      glyph: "▶",
    },
  },
  {
    id: "item_silver_hairclip",
    name: "銀色の髪留め",
    shortDescription: "銀杏とKが刻まれた細い髪留め",
    inventoryDescription: "雨に洗われた銀色の髪留め。裏側の銀杏とKの刻印はまだ鮮明。",
    objective: "雨のホームの排水溝を調べ、刻印に合う乗客へ髪留めを返す",
    stage: 3,
    spawn: {
      areaId: "area_rain_platform",
      hotspotId: "platform_drain_hairclip",
      position: { x: 650, y: 446 },
      availableFromStage: 3,
      requiresReturnedItemIds: [
        "item_red_umbrella",
        "item_star_bento",
        "item_cassette_player",
      ],
    },
    ownerId: "owner_ginkgo_student",
    clueIds: ["clue_hairclip_engraving", "clue_hairclip_bookmark_tag"],
    wrongDialogIds: [
      "dialog_item_silver_hairclip_wrong_1",
      "dialog_item_silver_hairclip_wrong_2",
    ],
    hintDialogIds: [
      "dialog_item_silver_hairclip_hint_1",
      "dialog_item_silver_hairclip_hint_2",
      "dialog_item_silver_hairclip_hint_3",
    ],
    memoryId: "memory_silver_hairclip",
    correctDialogId: "dialog_item_silver_hairclip_correct",
    note: "銀杏とKの刻印。跨線橋の学生は同じ印を持ち、右髪を気にしている。",
    visual: {
      shape: "hairclip",
      primaryColor: "#d5dbe2",
      secondaryColor: "#d2a84b",
      glyph: "K",
    },
  },
  {
    id: "item_faded_photo_sticker",
    name: "色あせた写真シール",
    shortDescription: "三日月とAM-042が残る二人の写真",
    inventoryDescription: "二人の顔が淡くかすれた写真シール。隅に三日月、裏にAM-042の印字。",
    objective: "再起動した待合室の写真機を調べ、破れた写真袋の持ち主を探す",
    stage: 4,
    spawn: {
      areaId: "area_waiting_room",
      hotspotId: "waiting_photo_booth_output",
      position: { x: 944, y: 282 },
      availableFromStage: 4,
      requiresReturnedItemIds: [
        "item_red_umbrella",
        "item_star_bento",
        "item_cassette_player",
        "item_silver_hairclip",
      ],
    },
    ownerId: "owner_crescent_youth",
    clueIds: ["clue_photo_crescent_pin", "clue_photo_booth_code"],
    wrongDialogIds: [
      "dialog_item_faded_photo_sticker_wrong_1",
      "dialog_item_faded_photo_sticker_wrong_2",
    ],
    hintDialogIds: [
      "dialog_item_faded_photo_sticker_hint_1",
      "dialog_item_faded_photo_sticker_hint_2",
      "dialog_item_faded_photo_sticker_hint_3",
    ],
    memoryId: "memory_faded_photo",
    correctDialogId: "dialog_item_faded_photo_sticker_correct",
    note: "三日月の印とAM-042。駅員室の青年が持つピンと破れた袋に一致する。",
    visual: {
      shape: "photo",
      primaryColor: "#d6bfa8",
      secondaryColor: "#65749b",
      glyph: "☾",
    },
  },
  {
    id: "item_blank_ticket",
    name: "行き先のない白紙の切符",
    shortDescription: "鏡像が先に持っていた未記名の切符",
    inventoryDescription: "行き先も日付もない白い切符。片端は、自分のポケットの紙片とつながる。",
    objective: "券売機の白紙の切符と自分の手がかりを照合し、本当の持ち主へ返す",
    stage: 5,
    spawn: {
      areaId: "area_concourse",
      hotspotId: "concourse_ticket_machine",
      position: { x: 772, y: 274 },
      availableFromStage: 5,
      requiresReturnedItemIds: [
        "item_red_umbrella",
        "item_star_bento",
        "item_cassette_player",
        "item_silver_hairclip",
        "item_faded_photo_sticker",
      ],
    },
    ownerId: "owner_nagi",
    clueIds: ["clue_ticket_pocket_fragment", "clue_ticket_reflection"],
    wrongDialogIds: [
      "dialog_item_blank_ticket_wrong_1",
      "dialog_item_blank_ticket_wrong_2",
    ],
    hintDialogIds: [
      "dialog_item_blank_ticket_hint_1",
      "dialog_item_blank_ticket_hint_2",
      "dialog_item_blank_ticket_hint_3",
    ],
    memoryId: "memory_blank_ticket",
    correctDialogId: "dialog_item_blank_ticket_correct",
    note: "ポケットの紙片、先回りする鏡像。最後の忘れものは、ナギ自身が置いてきた決意。",
    visual: {
      shape: "ticket",
      primaryColor: "#f0eee4",
      secondaryColor: "#7aa9c4",
      glyph: "→",
    },
  },
] as const;

export const STORY_OBJECTIVES: readonly ObjectiveDefinition[] = [
  {
    stage: 0,
    itemId: "item_red_umbrella",
    shortText: "待合室の赤い傘を調べる",
    noteText: "傘立ての周囲で、持ち主につながる二つの特徴を探そう。",
  },
  {
    stage: 1,
    itemId: "item_star_bento",
    shortText: "駅員室の冷蔵庫を調べる",
    noteText: "開いた駅員室と、紺の鞄の乗客を見比べよう。",
  },
  {
    stage: 2,
    itemId: "item_cassette_player",
    shortText: "跨線橋の回転音を探す",
    noteText: "雨音の拍子と、青い補修糸を覚えている人がいる。",
  },
  {
    stage: 3,
    itemId: "item_silver_hairclip",
    shortText: "雨のホームの細い光を調べる",
    noteText: "排水溝の忘れものに刻まれた印を、乗客の持ち物と照合しよう。",
  },
  {
    stage: 4,
    itemId: "item_faded_photo_sticker",
    shortText: "再起動した写真機へ戻る",
    noteText: "写真の印と番号は、破れた袋の持ち主につながる。",
  },
  {
    stage: 5,
    itemId: "item_blank_ticket",
    shortText: "白紙の切符の持ち主を見つける",
    noteText: "ポケットの紙片と、駅員室の鏡像を確かめよう。",
  },
  {
    stage: 6,
    itemId: null,
    shortText: "夜明けの行き先を選ぶ",
    noteText: "始発を待つか、この駅の灯りを守るか。ナギ自身の言葉で決めよう。",
  },
] as const;
