import type { OwnerDefinition } from "./types";

export const OWNER_DEFINITIONS: readonly OwnerDefinition[] = [
  {
    id: "owner_station_attendant",
    name: "顔の見えない駅員",
    role: "雨ノ間駅の案内役",
    areaId: "area_concourse",
    hotspotId: "concourse_station_attendant",
    position: { x: 548, y: 194 },
    profile: "古い紺の制服を着た駅員。帽子の影に顔は見えず、答えではなく次に見る場所を教える。",
    notebookObservation: "濡れていない制服。声は遠い構内放送と同じ響き。",
    ambientDialogId: "dialog_owner_station_attendant_ambient",
    returnedDialogId: "dialog_owner_station_attendant_returned",
    availableFromStage: 0,
    visual: {
      silhouetteColor: "#18263a",
      accentColor: "#d8bd72",
      accessory: "金縁の制帽",
    },
  },
  {
    id: "owner_red_boots_child",
    name: "赤い長靴の子",
    role: "窓辺で母を待つ小さな乗客",
    areaId: "area_waiting_room",
    hotspotId: "waiting_red_boots_child",
    position: { x: 824, y: 386 },
    profile: "赤い長靴と白い星のワッペンが目印。明かりの下から離れようとしない。",
    notebookObservation: "小さな靴は濡れている。上着の肘に白い星の補修。",
    ambientDialogId: "dialog_owner_child_ambient",
    returnedDialogId: "dialog_owner_child_returned",
    availableFromStage: 0,
    visual: {
      silhouetteColor: "#25334a",
      accentColor: "#d75858",
      accessory: "赤い長靴と星のワッペン",
    },
  },
  {
    id: "owner_navy_bag_commuter",
    name: "紺の鞄の通勤客",
    role: "妹への礼を言えなかった通勤客",
    areaId: "area_concourse",
    hotspotId: "concourse_navy_bag_commuter",
    position: { x: 822, y: 392 },
    profile: "きちんとした外套と大きな紺の鞄。眠る妹を起こさず町を出た朝を気にしている。",
    notebookObservation: "鞄の持ち手に、古い紺色の包み布が結ばれている。",
    ambientDialogId: "dialog_owner_commuter_ambient",
    returnedDialogId: "dialog_owner_commuter_returned",
    availableFromStage: 0,
    visual: {
      silhouetteColor: "#202f47",
      accentColor: "#425d82",
      accessory: "紺の旅行鞄",
    },
  },
  {
    id: "owner_old_listener",
    name: "耳を澄ます老人",
    role: "故郷の雨音を探す老人",
    areaId: "area_waiting_room",
    hotspotId: "waiting_old_listener",
    position: { x: 612, y: 226 },
    profile: "目を閉じ、指先で四拍を刻む老人。耳当ての片側を青い糸で直している。",
    notebookObservation: "四拍ずつ指を打つ。ヘッドホンの縫い糸は鮮やかな青。",
    ambientDialogId: "dialog_owner_old_listener_ambient",
    returnedDialogId: "dialog_owner_old_listener_returned",
    availableFromStage: 0,
    visual: {
      silhouetteColor: "#2c3444",
      accentColor: "#4f8fba",
      accessory: "青糸で直したヘッドホン",
    },
  },
  {
    id: "owner_ginkgo_student",
    name: "本を抱く学生",
    role: "別れの一行を読めない学生",
    areaId: "area_footbridge",
    hotspotId: "footbridge_ginkgo_student",
    position: { x: 770, y: 268 },
    profile: "厚い本を胸に抱き、右の髪を何度も耳へかける。鞄にはKの名札。",
    notebookObservation: "銀杏の栞、Kの名札、右髪を押さえる仕草。",
    ambientDialogId: "dialog_owner_student_ambient",
    returnedDialogId: "dialog_owner_student_returned",
    availableFromStage: 2,
    visual: {
      silhouetteColor: "#28354a",
      accentColor: "#d2a84b",
      accessory: "銀杏の栞を挟んだ本",
    },
  },
  {
    id: "owner_crescent_youth",
    name: "月のピンの青年",
    role: "未完の言葉を写真に残した青年",
    areaId: "area_station_office",
    hotspotId: "office_moon_youth",
    position: { x: 838, y: 380 },
    profile: "襟に三日月のピンを留め、破れた写真袋を握る青年。袋にはAM-042。",
    notebookObservation: "三日月のピン。写真袋の印字はAM-042で途中から破れている。",
    ambientDialogId: "dialog_owner_youth_ambient",
    returnedDialogId: "dialog_owner_youth_returned",
    availableFromStage: 1,
    visual: {
      silhouetteColor: "#222d43",
      accentColor: "#c9d2ec",
      accessory: "三日月の襟ピンと写真袋",
    },
  },
  {
    id: "owner_nagi",
    name: "ナギ",
    role: "白紙の切符を持つ主人公",
    areaId: "area_station_office",
    hotspotId: "office_mirror",
    position: { x: 554, y: 138 },
    profile: "濃紺の髪と湿った制服の高校生。名前以外の記憶を失い、鏡の中の自分だけが一拍先に動く。",
    notebookObservation: "拾う前から鏡像が白い紙を持つ。自分のポケットには同じ切断面の紙片。",
    ambientDialogId: "dialog_owner_nagi_ambient",
    returnedDialogId: "dialog_owner_nagi_returned",
    availableFromStage: 1,
    visual: {
      silhouetteColor: "#1b2e4b",
      accentColor: "#78a9c7",
      accessory: "濃紺の髪と白い切符",
    },
  },
] as const;
